/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const OrderLazyImport = createFileRoute('/order')()

// Create/Update Routes

const OrderLazyRoute = OrderLazyImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/order.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/order': typeof OrderLazyRoute
}

export interface FileRoutesByTo {
  '/order': typeof OrderLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/order': typeof OrderLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/order'
  fileRoutesByTo: FileRoutesByTo
  to: '/order'
  id: '__root__' | '/order'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  OrderLazyRoute: typeof OrderLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  OrderLazyRoute: OrderLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/order"
      ]
    },
    "/order": {
      "filePath": "order.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
